repos:
  - repo: local
    hooks:
      - id: no-placeholders
        name: No placeholders or duplicate lines
        entry: scripts/no_placeholders.py
        language: script
        files: '\.py$'
